###
GET localhost:8080/jobs
Accept: application/json
Accept-Charset: UTF-8

###
GET localhost:8080/companies
Accept: application/json
Accept-Charset: UTF-8

###
POST localhost:8080/companies
Accept: application/json
Accept-Charset: UTF-8
Content-Type: application/json
Content-Encoding: UTF-8

{
  "name": "ACME SA",
  "description": "Developing company"
}

###
POST localhost:8080/companies
Accept: application/json
Accept-Charset: UTF-8
Content-Type: application/json
Content-Encoding: UTF-8

{
"name": "TRANS SA",
"description": "Developing company"
}

###
POST localhost:8080/jobs
Accept: application/json
Accept-Charset: UTF-8
Content-Type: application/json
Content-Encoding: UTF-8

{
  "title": "Software Engineer",
  "description": "Developing applications",
  "minSalary": "30000",
  "maxSalary": "40000",
  "location": "New Jersey",
  "company": {
    "id": 1
  }
}

###
GET localhost:8080/jobs/1
Accept: application/json
Accept-Charset: UTF-8

###
GET localhost:8080/companies/2
Accept: application/json
Accept-Charset: UTF-8

###
GET localhost:8080/jobs/100
Accept: application/json
Accept-Charset: UTF-8

###
PUT localhost:8080/jobs/2
Accept: application/json
Accept-Charset: UTF-8
Content-Type: application/json
Content-Encoding: UTF-8

{
  "title": "Software Engineer Principal",
  "description": "Developing applications",
  "minSalary": "60000",
  "maxSalary": "80000",
  "location": "New Jersey",
  "company": { "id":  1 }
}

###
DELETE localhost:8080/jobs/1
Accept: application/json
Accept-Charset: UTF-8
