spring:
  application:
      name: jobapp
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/db
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    default-property-inclusion: non_empty
